routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::pattern('alias', '[\da-z-]+');

Auth::routes();

Route::post('send-recall', 'RecallController@recall')->name('send.recall');
Route::post('send-subscribe', 'SubscribeController@subscribe')->name('send.subscribe');
Route::post('send-order', 'OrderController@order')->name('send.order');

Route::get('{alias?}', 'PageController@show')->name('page.show');

Route::group(['prefix' => '_root', 'middleware' => 'auth', 'namespace' => 'Admin', 'as' => 'admin.'], static function () {

    Route::get('', 'HomeController@home')->name('home');
    Route::post('search', 'SearchController@search')->name('search');

    Route::post('upload-ckeditor', 'CkeditorController@upload')->name('upload-ckeditor');

    foreach (glob(app_path('Domain/**/routes.php')) as $item) {
        require $item;
    }
});

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section('content')

    <div class="panel panel-flat search_box">
        <div class="panel-body">
            <legend class="text-uppercase font-size-sm font-weight-bold">Поиск матчей</legend>
            <div class="content-group">
                <form action="{{ route('admin.search') }}" class="form-horizontal" method="post">
                    <div class="form-group">
                        <div class="col-lg-5">
                            @csrf
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Введите минимум три символа" minlength="3" required="" name="keyword">
                                <span class="input-group-addon"><i class="icon-search4"></i></span>
                            </div>
                        </div>
                        <label class="control-label col-lg-7" data-action="reload">Введите команду, чемпионат или стадион</label>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="panel panel-flat">
        <div class="panel-body">
            <div id="search_results"></div>
        </div>
    </div>

@endsection

resources/views/admin/search_results.blade.php
@if(count($matches))
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr class="border-solid">
            <th>#</th>
            <th>Команды матча</th>
            <th>Стадион</th>
            <th>Время начала матча</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($matches as $match)
            <tr>
                <td><span class="label label-primary">{{ $loop->iteration }}</span></td>
                <td>
                        <span class="label {{ ! $match->status ? 'label-danger not_active' : 'label-primary' }}">
                            {{ $match->teamFirst->name }} - {{ $match->teamSecond ? $match->teamSecond->name : '?' }}
                        </span>
                </td>
                <td><span class="label label-default">{{ $match->stadium->name}}</span></td>
                <td><span class="label label-success">{{ $match->start_datetime }}</span></td>
                <td>
                    <div>
                        <a href="{{ route('admin.matches.edit', $match) }}" class="last__btn" target="_blank"><i class="icon-pencil7"></i></a>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@else
<p>Результов нет</p>
@endif